#!/bin/sh
account="?????-???-??"
counter="????????????????"
login="???????%40mail.com"
password="????????"
pgu_link="https://pgu.mos.ru/ru/application/mosenergo/counters/"

################################

usage() {
    cat >&2 << EOF

Usage:
   $0 - get counter values
   $0 [Tariff1] [Tariff2] [Tariff3] - set values according to you tariff
EOF
}
setValue() {
	curl -c $cjar -b $cjar -s -d "$value$nm_abn" $pgu_link?getAction=sendData
}

#################################

cjar=`mktemp /tmp/elpgu-cookies.XXXX`
resp=`mktemp /tmp/elpgu-json.XXXX`
# get cookies
curl -c $cjar -s https://login.mos.ru/eaidit/eaiditweb/openouterlogin.do > /dev/null
# post login data
if ! curl -c $cjar -b $cjar -s -L -d "username=$login&password=$password" https://login.mos.ru/eaidit/eaiditweb/outerlogin.do | grep -q "Your login was successful"; then
	echo "Login failed!" >&2
	exit 1
fi
curl -c $cjar -b $cjar -s -d "getAction=auth&ls=$account&pu=$counter" $pgu_link > $resp
nm_abn=$(cat $resp | sed -r 's/^.*(..nm_abn.*)}}/\1/;s/\"//g;s/,/\&/g;s/:/=/g')

echo " "
echo "Current Counter Values"
cat $resp | sed -r 's/^.*currentCounts...(.*)...nm_abn.*$/\1/'
echo " "

if [ "$#" -eq 1 ]; then
	value="t1=$1"
	setValue
elif [ "$#" -eq 2 ]; then
	value="t1=$1&t2=$2"
	setValue
elif [ "$#" -eq 3 ]; then
	value="t1=$1&t2=$2&t3=$3"
	setValue
else
	usage
fi
	
rm $cjar $resp
