#!/bin/bash

login="???%40mail.com"
password="???"
account="?????-???-??"
counter="???"
################################
#################################

pgu_link="https://pgu.mos.ru/ru/application/mosenergo/counters/"
cjar=`mktemp /tmp/curl-elpgu-cookies.XXXX`
resp=`mktemp /tmp/curl-elpgu-json.XXXX`
# get cookies
curl -c $cjar -s https://login.mos.ru/eaidit/eaiditweb/openouterlogin.do > /dev/null
# post login data
if ! curl -c $cjar -b $cjar -s -L -d "username=$login&password=$password" https://login.mos.ru/eaidit/eaiditweb/outerlogin.do | grep -q "Your login was successful"; then
	echo "Login failed!" >&2
	exit 1
fi
# get counter values
curl -c $cjar -b $cjar -s -d "getAction=auth&ls=$account&pu=$counter" $pgu_link > $resp

if [ $# -gt 0 ]
then
	for arg in "$@"
	do
		(( i++ ))
		value="${value}t$i=$arg&"
	done
	nm_abn=$( cat $resp | sed -r 's/^.*(nm_abn.*)}}/\1/;s/\"//g;s/,/\&/g;s/:/=/g' )
	curl -c $cjar -b $cjar -s -d "$value$nm_abn" $pgu_link?getAction=sendData
else
	echo "Current Counter Values"
	cat $resp | sed 's/\"//g;s/:/=/g;s/,/\n/g' | grep ^count_t | sed 's/count_t/T/g'
	echo "Usage:   "$0" - get counter values and usage"
	echo "         "$0" [T1] [T2] [T3] - set values according to you tariff"
fi
rm $cjar $resp
